export const PROFESSIONS = [
{ id:"armorer", en:"Armorer", de:"Rüstungsschmied",
  station:{en:"Blast Furnace", de:"Kohleofen", slug:"blast-furnace",
    grid:[{i:"Iron Ingot"},{i:"Iron Ingot"},{i:"Iron Ingot"},{i:"Iron Ingot"},{i:"Furnace"},{i:"Iron Ingot"},{i:"Smooth Stone"},{i:"Smooth Stone"},{i:"Smooth Stone"}],
    note:"5× Eisenbarren + 1× Ofen + 3× Glatter Stein → 1 Kohleofen."},
  trades:[
    {lvl:1, want:[{n:15,i:"Coal"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:1, want:[{n:5,i:"Emerald"}], give:{n:1,i:"Iron Helmet"}, stock:12},
    {lvl:1, want:[{n:9,i:"Emerald"}], give:{n:1,i:"Iron Chestplate"}, stock:12},
    {lvl:1, want:[{n:7,i:"Emerald"}], give:{n:1,i:"Iron Leggings"}, stock:12},
    {lvl:1, want:[{n:4,i:"Emerald"}], give:{n:1,i:"Iron Boots"}, stock:12},
    {lvl:2, want:[{n:4,i:"Iron Ingot"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:2, want:[{n:36,i:"Emerald"}], give:{n:1,i:"Bell"}, stock:12},
    {lvl:2, want:[{n:3,i:"Emerald"}], give:{n:1,i:"Chainmail Leggings"}, stock:12},
    {lvl:2, want:[{n:1,i:"Emerald"}], give:{n:1,i:"Chainmail Boots"}, stock:12},
    {lvl:3, want:[{n:1,i:"Lava Bucket"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:3, want:[{n:1,i:"Diamond"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:3, want:[{n:1,i:"Emerald"}], give:{n:1,i:"Chainmail Helmet"}, stock:12},
    {lvl:3, want:[{n:4,i:"Emerald"}], give:{n:1,i:"Chainmail Chestplate"}, stock:12},
    {lvl:3, want:[{n:5,i:"Emerald"}], give:{n:1,i:"Shield"}, stock:12},
    {lvl:4, want:[{n:"19–33",i:"Emerald"}], give:{n:1,i:"Diamond Leggings"}, stock:3, note:"14 Basis + Level 5–19"},
    {lvl:4, want:[{n:"13–27",i:"Emerald"}], give:{n:1,i:"Diamond Boots"}, stock:3, note:"8 Basis + Level 5–19"},
    {lvl:5, want:[{n:"13–27",i:"Emerald"}], give:{n:1,i:"Diamond Helmet"}, stock:3, note:"8 Basis + Level 5–19"},
    {lvl:5, want:[{n:"21–35",i:"Emerald"}], give:{n:1,i:"Diamond Chestplate"}, stock:3, note:"16 Basis + Level 5–19"},
  ]},
{ id:"butcher", en:"Butcher", de:"Metzger",
  station:{en:"Smoker", de:"Räucherofen", slug:"smoker",
    grid:[null,{i:"Log"},null,{i:"Log"},{i:"Furnace"},{i:"Log"},null,{i:"Log"},null],
    note:"4× beliebige Stämme + 1× Ofen (Kreuz-Form) → 1 Räucherofen."},
  trades:[
    {lvl:1, want:[{n:14,i:"Raw Chicken"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:1, want:[{n:4,i:"Raw Rabbit"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:1, want:[{n:7,i:"Raw Porkchop"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:1, want:[{n:1,i:"Emerald"}], give:{n:1,i:"Rabbit Stew"}, stock:12},
    {lvl:2, want:[{n:15,i:"Coal"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:2, want:[{n:1,i:"Emerald"}], give:{n:8,i:"Cooked Chicken"}, stock:16},
    {lvl:2, want:[{n:1,i:"Emerald"}], give:{n:5,i:"Cooked Porkchop"}, stock:16},
    {lvl:3, want:[{n:10,i:"Raw Beef"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:3, want:[{n:7,i:"Raw Mutton"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:4, want:[{n:10,i:"Dried Kelp Block"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:5, want:[{n:10,i:"Sweet Berries"}], give:{n:1,i:"Emerald"}, stock:12},
  ]},
{ id:"cartographer", en:"Cartographer", de:"Kartograf",
  station:{en:"Cartography Table", de:"Kartografietisch", slug:"cartography-table",
    grid:[{i:"Paper"},{i:"Paper"},null,{i:"Wood Planks"},{i:"Wood Planks"},null,{i:"Wood Planks"},{i:"Wood Planks"},null],
    note:"2× Papier + 4× Bretter → 1 Kartografietisch."},
  trades:[
    {lvl:1, want:[{n:24,i:"Paper"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:1, want:[{n:7,i:"Emerald"}], give:{n:1,i:"Map"}, stock:12},
    {lvl:2, want:[{n:11,i:"Glass Pane"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:2, want:[{n:8,i:"Emerald"},{n:1,i:"Compass"}], give:{n:1,i:"Explorer Map"}, stock:12, note:"Biomeabhängig"},
    {lvl:3, want:[{n:1,i:"Compass"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:3, want:[{n:13,i:"Emerald"},{n:1,i:"Compass"}], give:{n:1,i:"Ocean Explorer Map"}, stock:12},
    {lvl:3, want:[{n:12,i:"Emerald"},{n:1,i:"Compass"}], give:{n:1,i:"Trial Explorer Map"}, stock:12},
    {lvl:4, want:[{n:7,i:"Emerald"}], give:{n:1,i:"Item Frame"}, stock:12},
    {lvl:4, want:[{n:3,i:"Emerald"}], give:{n:1,i:"Banner"}, stock:12, note:"Farbe biomeabhängig"},
    {lvl:5, want:[{n:8,i:"Emerald"}], give:{n:1,i:"Globe Banner Pattern"}, stock:12},
    {lvl:5, want:[{n:14,i:"Emerald"},{n:1,i:"Compass"}], give:{n:1,i:"Woodland Explorer Map"}, stock:12},
  ]},
{ id:"cleric", en:"Cleric", de:"Kleriker",
  station:{en:"Brewing Stand", de:"Braustand", slug:"brewing-stand",
    grid:[null,{i:"Blaze Rod"},null,null,null,null,{i:"Cobblestone"},{i:"Cobblestone"},{i:"Cobblestone"}],
    note:"1× Blaze-Rute + 3× Bruchstein → 1 Braustand."},
  trades:[
    {lvl:1, want:[{n:32,i:"Rotten Flesh"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:1, want:[{n:1,i:"Emerald"}], give:{n:2,i:"Redstone Dust"}, stock:12},
    {lvl:2, want:[{n:3,i:"Gold Ingot"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:2, want:[{n:1,i:"Emerald"}], give:{n:1,i:"Lapis Lazuli"}, stock:12},
    {lvl:3, want:[{n:2,i:"Rabbit's Foot"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:3, want:[{n:4,i:"Emerald"}], give:{n:1,i:"Glowstone"}, stock:12},
    {lvl:4, want:[{n:4,i:"Turtle Scute"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:4, want:[{n:9,i:"Glass Bottle"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:4, want:[{n:5,i:"Emerald"}], give:{n:1,i:"Ender Pearl"}, stock:12},
    {lvl:5, want:[{n:22,i:"Nether Wart"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:5, want:[{n:3,i:"Emerald"}], give:{n:1,i:"Bottle o' Enchanting"}, stock:12},
  ]},
{ id:"farmer", en:"Farmer", de:"Bauer",
  station:{en:"Composter", de:"Komposter", slug:"composter",
    grid:[{i:"Wood Slab"},null,{i:"Wood Slab"},{i:"Wood Slab"},null,{i:"Wood Slab"},{i:"Wood Slab"},{i:"Wood Slab"},{i:"Wood Slab"}],
    note:"7× Holzstufen (Kasten-Form, oben offen) → 1 Komposter."},
  trades:[
    {lvl:1, want:[{n:20,i:"Wheat"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:1, want:[{n:26,i:"Potato"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:1, want:[{n:22,i:"Carrot"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:1, want:[{n:15,i:"Beetroot"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:1, want:[{n:1,i:"Emerald"}], give:{n:6,i:"Bread"}, stock:16},
    {lvl:2, want:[{n:6,i:"Pumpkin"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:2, want:[{n:1,i:"Emerald"}], give:{n:4,i:"Pumpkin Pie"}, stock:12},
    {lvl:2, want:[{n:1,i:"Emerald"}], give:{n:4,i:"Apple"}, stock:16},
    {lvl:3, want:[{n:4,i:"Melon"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:3, want:[{n:3,i:"Emerald"}], give:{n:18,i:"Cookie"}, stock:12},
    {lvl:4, want:[{n:1,i:"Emerald"}], give:{n:1,i:"Suspicious Stew"}, stock:12},
    {lvl:4, want:[{n:1,i:"Emerald"}], give:{n:1,i:"Cake"}, stock:12},
    {lvl:5, want:[{n:3,i:"Emerald"}], give:{n:3,i:"Golden Carrot"}, stock:12},
    {lvl:5, want:[{n:4,i:"Emerald"}], give:{n:3,i:"Glistering Melon Slice"}, stock:12},
  ]},
{ id:"fisherman", en:"Fisherman", de:"Fischer",
  station:{en:"Barrel", de:"Fass", slug:"barrel",
    grid:[{i:"Wood Planks"},{i:"Wood Slab"},{i:"Wood Planks"},{i:"Wood Planks"},null,{i:"Wood Planks"},{i:"Wood Planks"},{i:"Wood Slab"},{i:"Wood Planks"}],
    note:"6× Bretter + 2× Holzstufen → 1 Fass."},
  trades:[
    {lvl:1, want:[{n:20,i:"String"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:1, want:[{n:10,i:"Coal"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:1, want:[{n:3,i:"Emerald"}], give:{n:1,i:"Bucket of Cod"}, stock:16},
    {lvl:1, want:[{n:6,i:"Raw Cod"},{n:1,i:"Emerald"}], give:{n:6,i:"Cooked Cod"}, stock:16},
    {lvl:2, want:[{n:15,i:"Raw Cod"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:2, want:[{n:2,i:"Emerald"}], give:{n:1,i:"Campfire"}, stock:12},
    {lvl:2, want:[{n:6,i:"Raw Salmon"},{n:1,i:"Emerald"}], give:{n:6,i:"Cooked Salmon"}, stock:16},
    {lvl:3, want:[{n:13,i:"Raw Salmon"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:3, want:[{n:"8–22",i:"Emerald"}], give:{n:1,i:"Fishing Rod"}, stock:3, note:"3 Basis + Level 5–19, verzaubert"},
    {lvl:4, want:[{n:6,i:"Tropical Fish"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:5, want:[{n:4,i:"Pufferfish"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:5, want:[{n:1,i:"Boat"}], give:{n:1,i:"Emerald"}, stock:12, note:"Bootstyp je nach Biom"},
  ]},
{ id:"fletcher", en:"Fletcher", de:"Bogner",
  station:{en:"Fletching Table", de:"Bognertisch", slug:"fletching-table",
    grid:[{i:"Flint"},{i:"Flint"},null,{i:"Wood Planks"},{i:"Wood Planks"},null,{i:"Wood Planks"},{i:"Wood Planks"},null],
    note:"2× Feuerstein + 4× Bretter → 1 Bognertisch."},
  trades:[
    {lvl:1, want:[{n:32,i:"Stick"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:1, want:[{n:1,i:"Emerald"}], give:{n:16,i:"Arrow"}, stock:12},
    {lvl:1, want:[{n:10,i:"Gravel"},{n:1,i:"Emerald"}], give:{n:10,i:"Flint"}, stock:12},
    {lvl:2, want:[{n:26,i:"Flint"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:2, want:[{n:2,i:"Emerald"}], give:{n:1,i:"Bow"}, stock:12},
    {lvl:3, want:[{n:14,i:"String"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:3, want:[{n:3,i:"Emerald"}], give:{n:1,i:"Crossbow"}, stock:12},
    {lvl:4, want:[{n:24,i:"Feather"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:4, want:[{n:"7–21",i:"Emerald"}], give:{n:1,i:"Bow"}, stock:3, note:"2 Basis + Level 5–19, verzaubert"},
    {lvl:5, want:[{n:8,i:"Tripwire Hook"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:5, want:[{n:"8–22",i:"Emerald"}], give:{n:1,i:"Crossbow"}, stock:3, note:"3 Basis + Level 5–19, verzaubert"},
    {lvl:5, want:[{n:2,i:"Emerald"},{n:5,i:"Arrow"}], give:{n:5,i:"Tipped Arrow"}, stock:12},
  ]},
{ id:"leatherworker", en:"Leatherworker", de:"Gerber",
  station:{en:"Cauldron", de:"Kessel", slug:"cauldron",
    grid:[{i:"Iron Ingot"},null,{i:"Iron Ingot"},{i:"Iron Ingot"},null,{i:"Iron Ingot"},{i:"Iron Ingot"},{i:"Iron Ingot"},{i:"Iron Ingot"}],
    note:"7× Eisenbarren (Kasten-Form, oben offen) → 1 Kessel."},
  trades:[
    {lvl:1, want:[{n:6,i:"Leather"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:1, want:[{n:3,i:"Emerald"}], give:{n:1,i:"Leather Pants"}, stock:12},
    {lvl:1, want:[{n:7,i:"Emerald"}], give:{n:1,i:"Leather Tunic"}, stock:12},
    {lvl:2, want:[{n:26,i:"Flint"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:2, want:[{n:5,i:"Emerald"}], give:{n:1,i:"Leather Cap"}, stock:12},
    {lvl:2, want:[{n:4,i:"Emerald"}], give:{n:1,i:"Leather Boots"}, stock:12},
    {lvl:3, want:[{n:9,i:"Rabbit Hide"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:3, want:[{n:7,i:"Emerald"}], give:{n:1,i:"Leather Tunic"}, stock:12},
    {lvl:4, want:[{n:4,i:"Turtle Scute"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:4, want:[{n:6,i:"Emerald"}], give:{n:1,i:"Leather Horse Armor"}, stock:12},
    {lvl:5, want:[{n:5,i:"Emerald"}], give:{n:1,i:"Leather Cap"}, stock:12},
    {lvl:5, want:[{n:6,i:"Emerald"}], give:{n:1,i:"Saddle"}, stock:12},
  ]},
{ id:"librarian", en:"Librarian", de:"Bibliothekar",
  station:{en:"Lectern", de:"Lesepult", slug:"lectern",
    grid:[{i:"Wood Slab"},{i:"Wood Slab"},{i:"Wood Slab"},null,{i:"Bookshelf"},null,null,{i:"Wood Slab"},null],
    note:"1× Bücherregal + 4× Holzstufen → 1 Lesepult."},
  hasEnchants:true,
  trades:[
    {lvl:1, want:[{n:24,i:"Paper"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:1, want:[{n:9,i:"Emerald"}], give:{n:1,i:"Bookshelf"}, stock:12},
    {lvl:2, want:[{n:4,i:"Book"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:2, want:[{n:1,i:"Emerald"}], give:{n:1,i:"Lantern"}, stock:12},
    {lvl:3, want:[{n:5,i:"Ink Sac"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:3, want:[{n:1,i:"Emerald"}], give:{n:4,i:"Glass"}, stock:12},
    {lvl:4, want:[{n:1,i:"Book and Quill"},{n:1,i:"Book and Quill"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:4, want:[{n:4,i:"Emerald"}], give:{n:1,i:"Compass"}, stock:12},
    {lvl:4, want:[{n:5,i:"Emerald"}], give:{n:1,i:"Clock"}, stock:12},
    {lvl:5, want:[{n:64,i:"Paper"}], give:{n:1,i:"Name Tag"}, stock:12, note:"seit Update 26.1"},
  ]},
{ id:"mason", en:"Mason", de:"Steinmetz",
  station:{en:"Stonecutter", de:"Steinsäge", slug:"stonecutter",
    grid:[null,{i:"Iron Ingot"},null,{i:"Stone"},{i:"Stone"},{i:"Stone"},null,null,null],
    note:"1× Eisenbarren + 3× Stein → 1 Steinsäge."},
  trades:[
    {lvl:1, want:[{n:10,i:"Clay Ball"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:1, want:[{n:1,i:"Emerald"}], give:{n:10,i:"Brick"}, stock:16},
    {lvl:2, want:[{n:20,i:"Stone"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:2, want:[{n:1,i:"Emerald"}], give:{n:4,i:"Chiseled Stone Bricks"}, stock:16},
    {lvl:3, want:[{n:16,i:"Granite"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:3, want:[{n:16,i:"Andesite"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:3, want:[{n:16,i:"Diorite"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:3, want:[{n:1,i:"Emerald"}], give:{n:4,i:"Dripstone Block"}, stock:16},
    {lvl:3, want:[{n:1,i:"Emerald"}], give:{n:4,i:"Polished Granite"}, stock:16},
    {lvl:4, want:[{n:12,i:"Nether Quartz"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:4, want:[{n:1,i:"Emerald"}], give:{n:1,i:"Stained Terracotta"}, stock:12, note:"beliebige Farbe"},
    {lvl:4, want:[{n:1,i:"Emerald"}], give:{n:1,i:"Glazed Terracotta"}, stock:12, note:"beliebige Farbe"},
    {lvl:5, want:[{n:1,i:"Emerald"}], give:{n:1,i:"Quartz Pillar"}, stock:12},
    {lvl:5, want:[{n:1,i:"Emerald"}], give:{n:1,i:"Block of Quartz"}, stock:12},
  ]},
{ id:"shepherd", en:"Shepherd", de:"Schäfer",
  station:{en:"Loom", de:"Webstuhl", slug:"loom",
    grid:[{i:"String"},{i:"String"},null,{i:"Wood Planks"},{i:"Wood Planks"},null,null,null,null],
    note:"2× Faden + 2× Bretter → 1 Webstuhl."},
  trades:[
    {lvl:1, want:[{n:18,i:"White Wool"}], give:{n:1,i:"Emerald"}, stock:16, note:"Farbe zufällig"},
    {lvl:1, want:[{n:2,i:"Emerald"}], give:{n:1,i:"Shears"}, stock:12},
    {lvl:2, want:[{n:12,i:"Dye"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:2, want:[{n:1,i:"Emerald"}], give:{n:1,i:"Colored Wool"}, stock:16, note:"beliebige Farbe"},
    {lvl:2, want:[{n:1,i:"Emerald"}], give:{n:4,i:"Colored Carpet"}, stock:16, note:"beliebige Farbe"},
    {lvl:3, want:[{n:3,i:"Emerald"}], give:{n:1,i:"Bed"}, stock:12, note:"beliebige Farbe"},
    {lvl:4, want:[{n:3,i:"Emerald"}], give:{n:1,i:"Banner"}, stock:12, note:"beliebige Farbe"},
    {lvl:5, want:[{n:2,i:"Emerald"}], give:{n:3,i:"Painting"}, stock:12},
  ]},
{ id:"toolsmith", en:"Toolsmith", de:"Werkzeugschmied",
  station:{en:"Smithing Table", de:"Schmiedetisch", slug:"smithing-table",
    grid:[{i:"Iron Ingot"},{i:"Iron Ingot"},null,{i:"Wood Planks"},{i:"Wood Planks"},null,{i:"Wood Planks"},{i:"Wood Planks"},null],
    note:"2× Eisenbarren + 4× Bretter → 1 Schmiedetisch."},
  trades:[
    {lvl:1, want:[{n:15,i:"Coal"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:1, want:[{n:1,i:"Emerald"}], give:{n:1,i:"Stone Axe"}, stock:12},
    {lvl:1, want:[{n:1,i:"Emerald"}], give:{n:1,i:"Stone Shovel"}, stock:12},
    {lvl:1, want:[{n:1,i:"Emerald"}], give:{n:1,i:"Stone Pickaxe"}, stock:12},
    {lvl:1, want:[{n:1,i:"Emerald"}], give:{n:1,i:"Stone Hoe"}, stock:12},
    {lvl:2, want:[{n:4,i:"Iron Ingot"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:2, want:[{n:36,i:"Emerald"}], give:{n:1,i:"Bell"}, stock:12},
    {lvl:3, want:[{n:30,i:"Flint"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:3, want:[{n:"6–20",i:"Emerald"}], give:{n:1,i:"Iron Axe"}, stock:3, note:"1 Basis + Level 5–19, verzaubert"},
    {lvl:3, want:[{n:"7–21",i:"Emerald"}], give:{n:1,i:"Iron Shovel"}, stock:3, note:"2 Basis + Level 5–19, verzaubert"},
    {lvl:3, want:[{n:"8–22",i:"Emerald"}], give:{n:1,i:"Iron Pickaxe"}, stock:3, note:"3 Basis + Level 5–19, verzaubert"},
    {lvl:3, want:[{n:4,i:"Emerald"}], give:{n:1,i:"Diamond Hoe"}, stock:3},
    {lvl:4, want:[{n:1,i:"Diamond"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:4, want:[{n:"17–31",i:"Emerald"}], give:{n:1,i:"Diamond Axe"}, stock:3, note:"12 Basis + Level 5–19, verzaubert"},
    {lvl:4, want:[{n:"10–24",i:"Emerald"}], give:{n:1,i:"Diamond Shovel"}, stock:3, note:"5 Basis + Level 5–19, verzaubert"},
    {lvl:5, want:[{n:"18–32",i:"Emerald"}], give:{n:1,i:"Diamond Pickaxe"}, stock:3, note:"13 Basis + Level 5–19, verzaubert"},
  ]},
{ id:"weaponsmith", en:"Weaponsmith", de:"Waffenschmied",
  station:{en:"Grindstone", de:"Schleifstein", slug:"grindstone",
    grid:[{i:"Wood Planks"},{i:"Stone Slab"},{i:"Wood Planks"},{i:"Stick"},null,{i:"Stick"},null,null,null],
    note:"2× Bretter + 1× Stein-Stufe + 2× Stöcke → 1 Schleifstein."},
  trades:[
    {lvl:1, want:[{n:15,i:"Coal"}], give:{n:1,i:"Emerald"}, stock:16},
    {lvl:1, want:[{n:3,i:"Emerald"}], give:{n:1,i:"Iron Axe"}, stock:12},
    {lvl:1, want:[{n:"7–21",i:"Emerald"}], give:{n:1,i:"Iron Sword"}, stock:3, note:"2 Basis + Level 5–19, verzaubert"},
    {lvl:2, want:[{n:4,i:"Iron Ingot"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:2, want:[{n:36,i:"Emerald"}], give:{n:1,i:"Bell"}, stock:12},
    {lvl:3, want:[{n:24,i:"Flint"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:4, want:[{n:1,i:"Diamond"}], give:{n:1,i:"Emerald"}, stock:12},
    {lvl:4, want:[{n:"17–31",i:"Emerald"}], give:{n:1,i:"Diamond Axe"}, stock:3, note:"12 Basis + Level 5–19, verzaubert"},
    {lvl:5, want:[{n:"13–27",i:"Emerald"}], give:{n:1,i:"Diamond Sword"}, stock:3, note:"8 Basis + Level 5–19, verzaubert"},
  ]}
];

export const DE = {
  "Coal":"Kohle","Emerald":"Smaragd","Iron Ingot":"Eisenbarren","Iron Helmet":"Eisenhelm","Iron Chestplate":"Eisenbrustplatte",
  "Iron Leggings":"Eisenhose","Iron Boots":"Eisenstiefel","Bell":"Glocke","Chainmail Leggings":"Kettenhose","Chainmail Boots":"Kettenstiefel",
  "Lava Bucket":"Lava-Eimer","Diamond":"Diamant","Chainmail Helmet":"Kettenhelm","Chainmail Chestplate":"Kettenbrustplatte","Shield":"Schild",
  "Diamond Leggings":"Diamanthose","Diamond Boots":"Diamantstiefel","Diamond Helmet":"Diamanthelm","Diamond Chestplate":"Diamantbrustplatte",
  "Raw Chicken":"Rohes Hühnchen","Raw Rabbit":"Rohes Kaninchen","Raw Porkchop":"Rohes Schweinefleisch","Rabbit Stew":"Kanincheneintopf",
  "Cooked Chicken":"Gebratenes Hühnchen","Cooked Porkchop":"Gebratenes Schweinefleisch","Raw Beef":"Rohes Rindfleisch","Raw Mutton":"Rohes Hammelfleisch",
  "Dried Kelp Block":"Getrockneter-Seetang-Block","Sweet Berries":"Süße Beeren",
  "Paper":"Papier","Map":"Karte","Glass Pane":"Glasscheibe","Compass":"Kompass","Explorer Map":"Entdeckerkarte","Ocean Explorer Map":"Ozean-Entdeckerkarte",
  "Trial Explorer Map":"Bewährungskammer-Karte","Item Frame":"Gegenstandsrahmen","Banner":"Banner","Globe Banner Pattern":"Globus-Bannermuster","Woodland Explorer Map":"Waldvilla-Karte",
  "Rotten Flesh":"Verwestes Fleisch","Redstone Dust":"Redstone-Staub","Gold Ingot":"Goldbarren","Lapis Lazuli":"Lapislazuli","Rabbit's Foot":"Kaninchenpfote",
  "Glowstone":"Leuchtstein","Turtle Scute":"Schildkrötenpanzerschuppe","Glass Bottle":"Glasflasche","Ender Pearl":"Enderperle","Nether Wart":"Netherwarze","Bottle o' Enchanting":"Erfahrungsfläschchen",
  "Wheat":"Weizen","Potato":"Kartoffel","Carrot":"Karotte","Beetroot":"Rote Bete","Bread":"Brot","Pumpkin":"Kürbis","Pumpkin Pie":"Kürbiskuchen","Apple":"Apfel",
  "Melon":"Melone","Cookie":"Keks","Suspicious Stew":"Verdächtiger Eintopf","Cake":"Kuchen","Golden Carrot":"Goldene Karotte","Glistering Melon Slice":"Glitzernde Melonenscheibe",
  "String":"Faden","Bucket of Cod":"Eimer mit Kabeljau","Raw Cod":"Roher Kabeljau","Cooked Cod":"Gebratener Kabeljau","Campfire":"Lagerfeuer","Raw Salmon":"Roher Lachs",
  "Cooked Salmon":"Gebratener Lachs","Fishing Rod":"Angel","Tropical Fish":"Tropenfisch","Pufferfish":"Kugelfisch","Boat":"Boot",
  "Stick":"Stock","Arrow":"Pfeil","Gravel":"Kies","Flint":"Feuerstein","Bow":"Bogen","Crossbow":"Armbrust","Feather":"Feder","Tripwire Hook":"Stolperdrahthaken","Tipped Arrow":"Getränkter Pfeil",
  "Leather":"Leder","Leather Pants":"Lederhose","Leather Tunic":"Lederjacke","Leather Cap":"Ledermütze","Leather Boots":"Lederstiefel","Rabbit Hide":"Kaninchenfell","Leather Horse Armor":"Lederpferderüstung","Saddle":"Sattel",
  "Book":"Buch","Bookshelf":"Bücherregal","Enchanted Book":"Verzaubertes Buch","Lantern":"Laterne","Ink Sac":"Tintenbeutel","Glass":"Glas","Book and Quill":"Buch und Feder","Clock":"Uhr","Name Tag":"Namensschild",
  "Clay Ball":"Tonklumpen","Brick":"Ziegel","Stone":"Stein","Chiseled Stone Bricks":"Gemeißelte Steinziegel","Granite":"Granit","Andesite":"Andesit","Diorite":"Diorit",
  "Dripstone Block":"Tropfstein-Block","Polished Granite":"Polierter Granit","Nether Quartz":"Netherquarz","Stained Terracotta":"Gefärbte Terrakotta","Glazed Terracotta":"Glasierte Terrakotta",
  "Quartz Pillar":"Quarzsäule","Block of Quartz":"Quarzblock",
  "White Wool":"Weiße Wolle","Shears":"Schere","Dye":"Farbstoff","Colored Wool":"Gefärbte Wolle","Colored Carpet":"Gefärbter Teppich","Bed":"Bett","Painting":"Gemälde",
  "Stone Axe":"Steinaxt","Stone Shovel":"Steinschaufel","Stone Pickaxe":"Steinspitzhacke","Stone Hoe":"Steinhacke","Iron Axe":"Eisenaxt","Iron Shovel":"Eisenschaufel","Iron Pickaxe":"Eisenspitzhacke",
  "Diamond Hoe":"Diamanthacke","Diamond Axe":"Diamantaxt","Diamond Shovel":"Diamantschaufel","Diamond Pickaxe":"Diamantspitzhacke","Iron Sword":"Eisenschwert","Diamond Sword":"Diamantschwert",
  "Log":"Stamm","Wood Planks":"Bretter","Wood Slab":"Holzstufe","Stone Slab":"Steinstufe","Furnace":"Ofen","Smooth Stone":"Glatter Stein","Cobblestone":"Bruchstein","Blaze Rod":"Blaze-Rute",
  "Anvil":"Amboss","Chest":"Truhe","Oak Log":"Eichenstamm","Oak Planks":"Eichenbretter","Mace":"Streitkolben"
};
export function deName(en){ return DE[en] || en; }
export const LVL_NAMES = {1:"Novize",2:"Lehrling",3:"Geselle",4:"Experte",5:"Meister"};
